#!/bin/sh
#
# git-noff-merge: merge without fast-forward
#
# Copyright (C) 2011 Ilkka Laukkanen <ilkka.s.laukkanen@gmail.com>

dashless=$(basename "$0" | sed -e 's/-/ /')
USAGE=
OPTIONS_SPEC=
SUBDIRECTORY_OK=
. git-sh-setup
require_work_tree

git merge --no-ff $@

