#!/bin/sh
#
# git-push-this: push current branch to remote
#
# Copyright (C) 2011 Ilkka Laukkanen <ilkka.s.laukkanen@gmail.com>
dashless=$(basename "$0" | sed -e 's/-/ /')
USAGE="[remote]"
OPTIONS_SPEC=
SUBDIRECTORY_OK=
. git-sh-setup
. git-parse-remote
require_work_tree
cd_to_toplevel

remote=$(get_default_remote)

if test $# -gt 1
then
	remote=$1
fi

if test -z "$remote"
then
	say "Unable to deduce remote"
	usage
fi

git push $remote HEAD:$(git current-branch)

